"""One-off builder: merge _i18n_merged.json + extras -> logic/ui_strings.json"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

data = json.loads((ROOT / "logic" / "_i18n_merged.json").read_text(encoding="utf-8"))

extra_en: dict[str, str] = {
    "wand_section_connection": "CONNECTION",
    "wand_serial": "SERIAL:",
    "wand_scan": "SCAN",
    "wand_connect": "CONNECT",
    "wand_disconnect": "DISCONNECT",
    "wand_no_ports": "No serial ports detected",
    "wand_section_terminal": "UART TERMINAL",
    "wand_clear": "CLEAR",
    "wand_section_stats": "DATASET STATISTICS",
    "wand_stats_waiting": "Awaiting connection...",
    "wand_no_data": "No data yet",
    "wand_section_payload": "FIRMWARE PAYLOAD",
    "wand_selected_title": "SELECTED FOR TRAINING",
    "wand_available_title": "AVAILABLE SPELLS",
    "wand_wait_sel": "Waiting for recorded spells",
    "wand_wait_avail": "Waiting for available spells",
    "wand_section_model": "MODEL BUILDING",
    "wand_build_tflite": "BUILD .TFLITE",
    "wand_build_cc": "BUILD .CC",
    "record_timeline": "TIMELINE:",
    "record_toolbar": "TOOLBAR",
    "record_spell_label": "Spell label:",
    "record_spell_placeholder": "Type or select spell name...",
    "record_hint_recorded": "Recorded",
    "record_hint_duration": "Duration",
    "record_selected_samples": "Selected: {n} samples",
    "record_start": "START",
    "record_stop": "STOP",
    "record_snip": "SNIP",
    "record_hint_controls": "START -> plot live (Ctrl+S)  |  STOP -> freeze & drag (Ctrl+T)  |  SNIP -> save (Ctrl+X)",
    "record_batch": "BATCH OPERATIONS",
    "record_clear": "CLEAR",
    "record_export": "EXPORT",
    "record_delete_latest": "DELETE LATEST",
    "record_tt_clear": "Clear all currently recorded samples",
    "record_tt_export": "Export recorded samples as CSV",
    "record_tt_delete_latest": "Quick delete the most recently saved sample for current spell",
    "record_tt_zoom_in": "Zoom in on plots",
    "record_tt_zoom_out": "Zoom out on plots",
    "record_tt_fit": "Fit plots to data",
    "record_show_accel": "SHOW ACCEL (aX, aY, aZ)",
    "record_show_gyro": "SHOW GYRO (gX, gY, gZ)",
    "record_wait_serial": "WAITING FOR SERIAL",
    "record_ready": "WAND IS READY",
    "record_not_ready": "WAND NOT READY",
    "record_spell_samples": "SAMPLES: {name}",
    "record_status_saved": "SAVED TO {name}",
    "record_select_spell": "Select a spell first",
    "record_enter_spell": "Enter a spell name first!",
    "record_invalid_crop": "Invalid crop region",
    "record_invalid_range": "Invalid selection range",
    "record_recording": "RECORDING DATA",
    "record_stopped_snip": "RECORDING STOPPED - Select region to snip",
    "record_cleared": "Recording buffer cleared",
    "record_no_export": "No samples to export",
    "record_exporting": "Exporting {n} samples...",
    "record_select_delete_spell": "Select a spell to delete its latest sample",
    "record_no_samples_spell": "No saved samples found for {name}",
    "record_deleting_latest": "Deleting latest sample from {name}...",
    "record_deleted_latest": "Latest sample deleted",
    "record_spell_protected": "{name} is protected",
    "record_clear_title": "Clear Recorded Samples",
    "record_clear_msg": "Clear all currently recorded samples?\n\nThis action cannot be undone.",
    "record_clear_confirm": "Clear All",
    "record_clear_cancel": "Keep Samples",
    "record_del_step1_title": "Delete Spell - Step 1",
    "record_del_step1_msg": "Delete the spell '{name}' and its training samples?\n\nThis removes the item from the visible library and prepares the final check.",
    "record_del_continue": "Continue",
    "record_del_keep": "Keep Spell",
    "record_del_step2_title": "Delete Spell - Step 2",
    "record_del_step2_msg": "Final confirmation: permanently delete spell '{name}' and all CSV samples on disk?",
    "record_del_final": "Delete permanently",
    "record_del_abort": "Cancel",
    "record_no_selection_title": "No Selection",
    "record_no_selection_msg": "Please select a spell to delete from the list.",
    "record_spell_list": "SPELL LIBRARY",
    "record_samples_title": "SAMPLES",
    "record_back": "BACK",
    "record_delete_spell_btn": "DELETE SPELL",
    "record_tt_delete_spell": "Delete selected spell and all samples",
    "record_tt_standby": "STAND BY is protected and cannot be deleted",
    "record_list_empty": "No spells available yet. Record and save a sample to populate the library.",
    "record_sample_empty": "No samples in this spell yet. Start recording and use SNIP to create one.",
    "stats_total_samples": "TOTAL SAMPLES: {n}",
    "stats_active_spells": "ACTIVE SPELLS: {n}",
    "stats_data_distribution": "DATA DISTRIBUTION",
    "stats_live_features": "LIVE FEATURES",
    "stats_model_train": "MODEL TRAIN / BUILD",
    "stats_train_idle": "Train: idle",
    "stats_build_idle": "Build: idle",
    "stats_train_run": "Train: running...",
    "stats_build_wait": "Build: waiting...",
    "stats_build_done": "Build: completed",
    "stats_btn_train": "TRAIN + BUILD GESTURE MODEL",
    "stats_btn_audit": "RUN DATASET HEALTH AUDIT",
    "stats_fft_header": "FREQUENCY SPECTRUM",
    "stats_fft_wait_features": "Waiting for live features…",
    "stats_dominant_wait": "Dominant: waiting for data",
    "stats_dominant_hz": "Dominant: {f:.1f} Hz",
    "stats_dominant_na": "Dominant: -- Hz",
    "stats_fft_unavailable": "Dominant: spectrum unavailable",
    "stats_plot_fft_mag": "FFT magnitude",
    "stats_plot_freq": "Frequency (Hz)",
    "stats_accel_tpl": "Accel: mean {m:.3f}  var {v:.3f}  rms {r:.3f}",
    "stats_gyro_tpl": "Gyro: mean {m:.3f}  var {v:.3f}  rms {r:.3f}",
    "stats_spell_mastery": "SPELL MASTERY",
    "stats_empty_mastery_title": "No spell data yet",
    "stats_empty_mastery_body": "Capture your first samples in Record, then return here to inspect distribution and rarity tiers.",
    "stats_samples_title": "SAMPLES: —",
    "stats_back": "BACK",
    "stats_no_samples_line": "No samples for this spell yet. Record one from the Record screen.",
    "stats_model_err_title": "Model build error",
    "stats_model_err_body": "Training or build failed. Check the status details and retry after fixing data or environment issues.",
    "primitive_signal_preview": "SIGNAL PREVIEW",
    "primitive_quality": "DATA QUALITY CHECK",
    "primitive_quality_none": "No data to evaluate yet",
    "primitive_encoder": "ENCODER TRAINING",
    "primitive_btn_train": "TRAIN ENCODER MODEL",
    "primitive_hint_train": "Collect all primitive groups first, then train the encoder.",
    "primitive_title": "PRIMITIVE GESTURE COLLECTION",
    "primitive_subtitle": "Structured capture for encoder training",
    "common_cancel": "Cancel",

    # Navigation
    "nav_home": "The Threshold",
    "nav_primitives": "The Fundamentals",
    "nav_record": "Scribe",
    "nav_wand": "Laboratory",
    "nav_settings": "Mechanisms",
    "nav_home_editorial": "The Threshold",
    "nav_primitives_editorial": "The Fundamentals",
    "nav_record_editorial": "Scribe",
    "nav_wand_editorial": "Laboratory",
    "nav_settings_editorial": "Mechanisms",
    "home_tip_title": "PRO SPELLCASTER TIP",
    "home_hero_subtitle": "REAL-TIME SPELL RECOGNITION",
    "home_hero_idle": "WAITING FOR SPELL...",
    "home_history_title": "RECENT SPELL HISTORY",
    "home_history_empty": "No Spells Recognized Yet",
    "home_loaded_title": "SPELLS LOADED THIS SESSION",
    "home_loaded_empty": "No Spells Loaded",
    "home_spell_count": "{count} Spells Registered",
    "home_samples_count": "{count} samples",
    "time_just_now": "Just now",
    "time_seconds_ago": "{n}s ago",
    "time_minutes_ago": "{n}m ago",
    "time_hours_ago": "{n}h ago",

    # Primitive collection page
    "primitive_btn_capture": "RECORD SAMPLE",
    "primitive_flow_hint": "Perform the primitive gesture carefully to record clean IMU sensor data.",

    # Record page
    "record_btn_back": "BACK",
    "record_btn_clear": "CLEAR ALL",
    "record_btn_export": "EXPORT CSV",
    "record_btn_snip": "SNIP SAMPLE",
    "record_btn_start": "START RECORDING",
    "record_btn_stop": "STOP RECORDING",
    "record_protected_msg": "Built-in primitive gestures cannot be modified.",
    "record_protected_title": "Protected Gesture",
    "record_recording_short": "RECORDING...",
    "record_snipped": "Sample snipped successfully",

    # Wand page
    "wand_build_firmware": "BUILD FIRMWARE",
    "wand_flash_ready": "Firmware ready to flash",
    "wand_status_connected": "WAND CONNECTED",
    "wand_status_connected_port": "WAND CONNECTED ({port})",
    "wand_status_disconnected": "WAND DISCONNECTED",
    "wand_upload_model": "UPLOAD MODEL",
}

extra_vi: dict[str, str] = {
    "wand_section_connection": "KẾT NỐI",
    "wand_serial": "SERIAL:",
    "wand_scan": "QUÉT",
    "wand_connect": "KẾT NỐI",
    "wand_disconnect": "NGẮT",
    "wand_no_ports": "Không phát hiện cổng serial",
    "wand_section_terminal": "TERMINAL UART",
    "wand_clear": "XÓA",
    "wand_section_stats": "THỐNG KÊ DATASET",
    "wand_stats_waiting": "Đang chờ kết nối...",
    "wand_no_data": "Chưa có dữ liệu",
    "wand_section_payload": "PAYLOAD FIRMWARE",
    "wand_selected_title": "ĐÃ CHỌN ĐỂ HUẤN LUYỆN",
    "wand_available_title": "SPELL KHẢ DỤNG",
    "wand_wait_sel": "Đang chờ spell đã ghi",
    "wand_wait_avail": "Đang chờ spell khả dụng",
    "wand_section_model": "BUILD MODEL",
    "wand_build_tflite": "BUILD .TFLITE",
    "wand_build_cc": "BUILD .CC",
    "record_timeline": "DÒNG THỜI GIAN:",
    "record_toolbar": "THANH CÔNG CỤ",
    "record_spell_label": "Nhãn spell:",
    "record_spell_placeholder": "Gõ hoặc chọn tên spell...",
    "record_hint_recorded": "Đã ghi",
    "record_hint_duration": "Thời lượng",
    "record_selected_samples": "Đã chọn: {n} mẫu",
    "record_start": "BẮT ĐẦU",
    "record_stop": "DỪNG",
    "record_snip": "CẮT",
    "record_hint_controls": "BẮT ĐẦU -> vẽ trực tiếp (Ctrl+S)  |  DỪNG -> đóng băng & kéo (Ctrl+T)  |  CẮT -> lưu (Ctrl+X)",
    "record_batch": "THAO TÁC HÀNG LOẠT",
    "record_clear": "XÓA",
    "record_export": "XUẤT",
    "record_delete_latest": "XÓA MỚI NHẤT",
    "record_tt_clear": "Xóa toàn bộ mẫu đang ghi trong bộ đệm",
    "record_tt_export": "Xuất mẫu đã ghi ra CSV",
    "record_tt_delete_latest": "Xóa nhanh mẫu mới nhất của spell hiện tại",
    "record_tt_zoom_in": "Phóng to đồ thị",
    "record_tt_zoom_out": "Thu nhỏ đồ thị",
    "record_tt_fit": "Vừa khung dữ liệu",
    "record_show_accel": "HIỆN GIA TỐC (aX, aY, aZ)",
    "record_show_gyro": "HIỆN CON QUAY (gX, gY, gZ)",
    "record_wait_serial": "CHỜ SERIAL",
    "record_ready": "ĐŨA PHÉP SẴN SÀNG",
    "record_not_ready": "ĐŨA PHÉP CHƯA SẴN SÀNG",
    "record_spell_samples": "MẪU: {name}",
    "record_status_saved": "ĐÃ LƯU VÀO {name}",
    "record_select_spell": "Chọn spell trước",
    "record_enter_spell": "Nhập tên spell trước!",
    "record_invalid_crop": "Vùng cắt không hợp lệ",
    "record_invalid_range": "Vùng chọn không hợp lệ",
    "record_recording": "ĐANG GHI DỮ LIỆU",
    "record_stopped_snip": "ĐÃ DỪNG GHI — Chọn vùng để cắt",
    "record_cleared": "Đã xóa bộ đệm ghi",
    "record_no_export": "Không có mẫu để xuất",
    "record_exporting": "Đang xuất {n} mẫu...",
    "record_select_delete_spell": "Chọn spell để xóa mẫu mới nhất",
    "record_no_samples_spell": "Không có mẫu cho {name}",
    "record_deleting_latest": "Đang xóa mẫu mới nhất của {name}...",
    "record_deleted_latest": "Đã xóa mẫu mới nhất",
    "record_spell_protected": "{name} được bảo vệ",
    "record_clear_title": "Xóa mẫu đã ghi",
    "record_clear_msg": "Xóa toàn bộ mẫu đang trong bộ đệm?\n\nKhông hoàn tác.",
    "record_clear_confirm": "Xóa tất cả",
    "record_clear_cancel": "Giữ lại",
    "record_del_step1_title": "Xóa spell — Bước 1",
    "record_del_step1_msg": "Xóa spell '{name}' và các mẫu huấn luyện?\n\nMục sẽ biến mất khỏi thư viện và cần xác nhận lần 2.",
    "record_del_continue": "Tiếp tục",
    "record_del_keep": "Giữ spell",
    "record_del_step2_title": "Xóa spell — Bước 2",
    "record_del_step2_msg": "Xác nhận cuối: xóa vĩnh viễn spell '{name}' và mọi file CSV trên đĩa?",
    "record_del_final": "Xóa vĩnh viễn",
    "record_del_abort": "Hủy",
    "record_no_selection_title": "Chưa chọn",
    "record_no_selection_msg": "Hãy chọn một spell trong danh sách để xóa.",
    "record_spell_list": "THƯ VIỆN SPELL",
    "record_samples_title": "MẪU",
    "record_back": "QUAY LẠI",
    "record_delete_spell_btn": "XÓA SPELL",
    "record_tt_delete_spell": "Xóa spell đã chọn và mọi mẫu",
    "record_tt_standby": "STAND BY được bảo vệ, không thể xóa",
    "record_list_empty": "Chưa có spell. Ghi và lưu mẫu để tạo thư viện.",
    "record_sample_empty": "Chưa có mẫu trong spell này. Bắt đầu ghi và dùng CẮT để tạo mẫu.",
    "stats_total_samples": "TỔNG MẪU: {n}",
    "stats_active_spells": "SPELL HOẠT ĐỘNG: {n}",
    "stats_data_distribution": "PHÂN BỐ DỮ LIỆU",
    "stats_live_features": "ĐẶC TRƯNG TRỰC TIẾP",
    "stats_model_train": "HUẤN LUYỆN / BUILD MODEL",
    "stats_train_idle": "Huấn luyện: chờ",
    "stats_build_idle": "Build: chờ",
    "stats_train_run": "Huấn luyện: đang chạy...",
    "stats_build_wait": "Build: đang chờ...",
    "stats_build_done": "Build: hoàn tất",
    "stats_btn_train": "HUẤN LUYỆN + BUILD MODEL GESTURE",
    "stats_btn_audit": "KIỂM TRA SỨC KHỎE DATASET",
    "stats_fft_header": "PHỔ TẦN SỐ",
    "stats_fft_wait_features": "Đang chờ đặc trưng trực tiếp…",
    "stats_dominant_wait": "Tần chủ: chờ dữ liệu",
    "stats_dominant_hz": "Tần chủ: {f:.1f} Hz",
    "stats_dominant_na": "Tần chủ: -- Hz",
    "stats_fft_unavailable": "Tần chủ: không có phổ",
    "stats_plot_fft_mag": "Biên độ FFT",
    "stats_plot_freq": "Tần số (Hz)",
    "stats_accel_tpl": "Gia tốc: trung bình {m:.3f}  phương sai {v:.3f}  rms {r:.3f}",
    "stats_gyro_tpl": "Con quay: trung bình {m:.3f}  phương sai {v:.3f}  rms {r:.3f}",
    "stats_spell_mastery": "THÀNH THẠO SPELL",
    "stats_empty_mastery_title": "Chưa có dữ liệu spell",
    "stats_empty_mastery_body": "Thu mẫu đầu tiên ở trang Ghi mẫu, rồi quay lại để xem phân bố và độ hiếm.",
    "stats_samples_title": "MẪU: —",
    "stats_back": "QUAY LẠI",
    "stats_no_samples_line": "Chưa có mẫu cho spell này. Ghi ở trang Ghi mẫu.",
    "stats_model_err_title": "Lỗi build model",
    "stats_model_err_body": "Huấn luyện hoặc build thất bại. Xem chi tiết và thử lại sau khi sửa dữ liệu hoặc môi trường.",
    "primitive_signal_preview": "XEM TRƯỚC TÍN HIỆU",
    "primitive_quality": "KIỂM TRA CHẤT LƯỢNG DỮ LIỆU",
    "primitive_quality_none": "Chưa có dữ liệu để đánh giá",
    "primitive_encoder": "HUẤN LUYỆN ENCODER",
    "primitive_btn_train": "HUẤN LUYỆN MODEL ENCODER",
    "primitive_hint_train": "Thu đủ các nhóm nguyên mẫu trước, rồi huấn luyện encoder.",
    "primitive_title": "THU THẬP GESTURE NGUYÊN MẪU",
    "primitive_subtitle": "Thu có cấu trúc cho huấn luyện encoder",
    "common_cancel": "Hủy",

    # Navigation
    "nav_home": "Trang Chủ",
    "nav_primitives": "Nguyên Mẫu",
    "nav_record": "Ghi Mẫu",
    "nav_wand": "Đũa Phép",
    "nav_settings": "Cài Đặt",
    "nav_home_editorial": "Trang Chủ",
    "nav_primitives_editorial": "Nguyên Mẫu",
    "nav_record_editorial": "Ghi Mẫu",
    "nav_wand_editorial": "Đũa Phép",
    "nav_settings_editorial": "Cài Đặt",
    "home_tip_title": "GỢI Ý THẦN CHÚ",
    "home_hero_subtitle": "NHẬN DIỆN THẦN CHÚ THỜI GIAN THỰC",
    "home_hero_idle": "ĐANG CHỜ THẦN CHÚ...",
    "home_history_title": "LỊCH SỬ NHẬN DIỆN GẦN ĐÂY",
    "home_history_empty": "Chưa Có Thần Chú Nào Được Ghi Nhận",
    "home_loaded_title": "THẦN CHÚ ĐÃ TẢI TRONG PHIÊN",
    "home_loaded_empty": "Chưa Tải Thần Chú Nào",
    "home_spell_count": "{count} Thần Chú Đã Đăng Ký",
    "home_samples_count": "{count} mẫu",
    "time_just_now": "Vừa xong",
    "time_seconds_ago": "{n} giây trước",
    "time_minutes_ago": "{n} phút trước",
    "time_hours_ago": "{n} giờ trước",

    # Primitive collection page
    "primitive_btn_capture": "GHI MẪU",
    "primitive_flow_hint": "Thực hiện cử chỉ nguyên thủy cẩn thận để ghi dữ liệu cảm biến IMU chuẩn xác.",

    # Record page
    "record_btn_back": "QUAY LẠI",
    "record_btn_clear": "XÓA TOÀN BỘ",
    "record_btn_export": "XUẤT FILE CSV",
    "record_btn_snip": "CẮT MẪU",
    "record_btn_start": "BẮT ĐẦU GHI",
    "record_btn_stop": "DỪNG GHI",
    "record_protected_msg": "Các cử chỉ nguyên thủy có sẵn không thể chỉnh sửa.",
    "record_protected_title": "Cử Chỉ Được Bảo Vệ",
    "record_recording_short": "ĐANG GHI...",
    "record_snipped": "Đã cắt mẫu thành công",

    # Wand page
    "wand_build_firmware": "BUILD FIRMWARE",
    "wand_flash_ready": "Firmware sẵn sàng nạp",
    "wand_status_connected": "ĐŨA PHÉP ĐÃ KẾT NỐI",
    "wand_status_connected_port": "ĐŨA PHÉP ĐÃ KẾT NỐI ({port})",
    "wand_status_disconnected": "ĐŨA PHÉP CHƯA KẾT NỐI",
    "wand_upload_model": "TẢI MÔ HÌNH LÊN ĐŨA",
}

data["en"].update(extra_en)
data["vi"].update(extra_vi)

out = ROOT / "logic" / "ui_strings.json"
out.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print("written", out, "keys", len(data["en"]))
