from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from constants import canonical_system_spell, normalize_spell_name


_TEMPLATE_ENUM = "{{SPELL_ENUM_BLOCK}}"
_TEMPLATE_NAMES = "{{SPELL_NAME_TABLE_BLOCK}}"
_TEMPLATE_SWITCH = "{{SPELL_SWITCH_BLOCK}}"
_TEMPLATE_COUNT = "{{SPELL_CLASS_COUNT}}"
_TEMPLATE_IDLE_INDEX = "{{SPELL_IDLE_INDEX}}"
_TEMPLATE_DISPATCH = "{{SPELL_DISPATCH_CASES}}"
_TEMPLATE_METADATA = "{{AUTOGEN_METADATA}}"


@dataclass(frozen=True)
class FirmwareSyncResult:
    main_cpp_path: str
    gesture_cc_path: str
    backup_path: str | None
    class_count: int


def _spell_identifier(spell_name: str) -> str:
    normalized = canonical_system_spell(normalize_spell_name(spell_name))
    cleaned = re.sub(r"[^A-Z0-9]+", "_", normalized.upper()).strip("_")
    if not cleaned:
        cleaned = "UNKNOWN"
    if cleaned[0].isdigit():
        cleaned = f"SPELL_{cleaned}"
    return cleaned


def _is_idle_spell(spell_name: str) -> bool:
    normalized = normalize_spell_name(spell_name)
    if canonical_system_spell(normalized) == "STAND BY":
        return True
    return normalized.startswith("IDLE")


def _render_main_cpp(template_text: str, class_names: list[str]) -> str:
    if not class_names:
        class_names = ["UNKNOWN"]

    rendered: list[tuple[int, str, str]] = []
    seen_identifiers: set[str] = set()
    for index, name in enumerate(class_names):
        base = _spell_identifier(name)
        ident = base
        suffix = 2
        while ident in seen_identifiers:
            ident = f"{base}_{suffix}"
            suffix += 1
        seen_identifiers.add(ident)
        rendered.append((index, str(name), ident))

    enum_rendered = list(rendered)
    if "UNKNOWN" not in seen_identifiers:
        enum_rendered.append((len(enum_rendered), "UNKNOWN", "UNKNOWN"))

    enum_lines = [f"  {ident}," for _, _, ident in enum_rendered]
    name_lines = [f'  "{name}",' for _, name, _ in rendered]
    switch_lines = [f"    case {index}: return SpellId::{ident};" for index, _, ident in rendered]
    dispatch_lines: list[str] = []
    for _, _, ident in rendered:
        dispatch_lines.append(f"    case SpellId::{ident}:")
        dispatch_lines.append("      break;")

    idle_index = -1
    for index, name, _ in rendered:
        if _is_idle_spell(name):
            idle_index = index
            break

    metadata = (
        f"Generated by STEM AI model build pipeline at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} "
        f"| classes={','.join(name for _, name, _ in rendered)}"
    )

    output = template_text
    output = output.replace(_TEMPLATE_ENUM, "\n".join(enum_lines))
    output = output.replace(_TEMPLATE_NAMES, "\n".join(name_lines))
    output = output.replace(_TEMPLATE_SWITCH, "\n".join(switch_lines))
    output = output.replace(_TEMPLATE_COUNT, str(len(rendered)))
    output = output.replace(_TEMPLATE_IDLE_INDEX, str(idle_index))
    output = output.replace(_TEMPLATE_DISPATCH, "\n".join(dispatch_lines))
    output = output.replace(_TEMPLATE_METADATA, metadata)

    return output


def _write_atomic_with_backup(target_path: Path, content: str) -> str | None:
    target_path.parent.mkdir(parents=True, exist_ok=True)
    backup_path: str | None = None

    if target_path.exists():
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_target = target_path.with_name(f"{target_path.name}.bak_{timestamp}")
        shutil.copyfile(target_path, backup_target)
        backup_path = str(backup_target)

    temp_path = target_path.with_name(f"{target_path.name}.tmp")
    temp_path.write_text(content, encoding="utf-8", newline="\n")
    temp_path.replace(target_path)

    return backup_path


def generate_main_cpp(
    *,
    idf_main_dir: Path,
    class_names: list[str],
    template_path: Path,
) -> tuple[str, str | None, int]:
    template_text = template_path.read_text(encoding="utf-8")
    rendered = _render_main_cpp(template_text, class_names)
    main_cpp_path = idf_main_dir / "main.cpp"
    backup = _write_atomic_with_backup(main_cpp_path, rendered)
    return str(main_cpp_path), backup, len(class_names)


def sync_firmware_sources(
    *,
    idf_main_dir: Path,
    generated_cc_path: Path,
    class_names: list[str],
    template_path: Path,
) -> FirmwareSyncResult:
    idf_main = idf_main_dir.expanduser().resolve()
    if not idf_main.exists() or not idf_main.is_dir():
        raise FileNotFoundError(f"IDF main directory not found: {idf_main}")

    idf_root = idf_main.parent
    if not (idf_root / "CMakeLists.txt").exists():
        raise FileNotFoundError(f"Missing CMakeLists.txt in IDF project root: {idf_root}")

    if idf_main.name.lower() != "main":
        raise ValueError("IDF path must point to the main directory")

    if not generated_cc_path.exists() or not generated_cc_path.is_file():
        raise FileNotFoundError(f"Generated gesture_model.cc not found: {generated_cc_path}")

    gesture_cc_target = idf_main / "gesture_model.cc"
    shutil.copyfile(generated_cc_path, gesture_cc_target)

    main_cpp_path, backup_path, class_count = generate_main_cpp(
        idf_main_dir=idf_main,
        class_names=class_names,
        template_path=template_path,
    )

    return FirmwareSyncResult(
        main_cpp_path=main_cpp_path,
        gesture_cc_path=str(gesture_cc_target),
        backup_path=backup_path,
        class_count=class_count,
    )
