from __future__ import annotations

from pathlib import Path

from logic.firmware_main_generator import sync_firmware_sources


def test_sync_firmware_sources_overwrites_main_cpp_and_copies_cc(tmp_path) -> None:
    idf_root = tmp_path / "idf_project"
    main_dir = idf_root / "main"
    main_dir.mkdir(parents=True)
    (idf_root / "CMakeLists.txt").write_text("cmake_minimum_required(VERSION 3.16)\n", encoding="utf-8")
    (main_dir / "main.cpp").write_text("legacy_main_content\n", encoding="utf-8")

    generated_cc = tmp_path / "gesture_model.cc"
    generated_cc.write_text("const int g_model_len = 1;\n", encoding="utf-8")

    template = tmp_path / "main.cpp.template"
    template.write_text(
        "// {{AUTOGEN_METADATA}}\n"
        "enum class SpellId {\n{{SPELL_ENUM_BLOCK}}\n};\n"
        "const char* kSpellNames[] = {\n{{SPELL_NAME_TABLE_BLOCK}}\n};\n"
        "constexpr int kSpellClassCount = {{SPELL_CLASS_COUNT}};\n"
        "constexpr int kIdleClassIndex = {{SPELL_IDLE_INDEX}};\n"
        "SpellId SpellFromIndex(int class_index) {\n  switch (class_index) {\n{{SPELL_SWITCH_BLOCK}}\n    default: return SpellId::UNKNOWN;\n  }\n}\n"
        "void Dispatch(SpellId spell) {\n  switch (spell) {\n{{SPELL_DISPATCH_CASES}}\n    default: break;\n  }\n}\n",
        encoding="utf-8",
    )

    result = sync_firmware_sources(
        idf_main_dir=main_dir,
        generated_cc_path=generated_cc,
        class_names=["PULSE", "STAND BY"],
        template_path=template,
    )

    rendered_main = Path(result.main_cpp_path).read_text(encoding="utf-8")
    copied_cc = Path(result.gesture_cc_path).read_text(encoding="utf-8")

    assert "SpellId::PULSE" in rendered_main
    assert "SpellId::STAND_BY" in rendered_main
    assert "SpellId::UNKNOWN" in rendered_main
    assert "kSpellClassCount = 2" in rendered_main
    assert "kIdleClassIndex = 1" in rendered_main
    assert "Generated by STEM AI model build pipeline" in rendered_main
    assert copied_cc == "const int g_model_len = 1;\n"
    assert result.backup_path is not None
    assert Path(result.backup_path).exists()


def test_sync_firmware_sources_handles_identifier_edge_cases(tmp_path) -> None:
    idf_root = tmp_path / "idf_project"
    main_dir = idf_root / "main"
    main_dir.mkdir(parents=True)
    (idf_root / "CMakeLists.txt").write_text("cmake_minimum_required(VERSION 3.16)\n", encoding="utf-8")
    (main_dir / "main.cpp").write_text("old\n", encoding="utf-8")

    generated_cc = tmp_path / "gesture_model.cc"
    generated_cc.write_text("const unsigned char g_model[] = {0};\nconst int g_model_len = 1;\n", encoding="utf-8")

    template = tmp_path / "main.cpp.template"
    template.write_text(
        "enum class SpellId {\n{{SPELL_ENUM_BLOCK}}\n};\n"
        "constexpr int kIdleClassIndex = {{SPELL_IDLE_INDEX}};\n"
        "SpellId SpellFromIndex(int class_index) {\n  switch (class_index) {\n{{SPELL_SWITCH_BLOCK}}\n    default: return SpellId::UNKNOWN;\n  }\n}\n",
        encoding="utf-8",
    )

    result = sync_firmware_sources(
        idf_main_dir=main_dir,
        generated_cc_path=generated_cc,
        class_names=["2fast", "2fast", "idle-normal"],
        template_path=template,
    )

    rendered_main = Path(result.main_cpp_path).read_text(encoding="utf-8")

    assert "SPELL_2FAST" in rendered_main
    assert "SPELL_2FAST_2" in rendered_main
    assert "IDLE_NORMAL" in rendered_main
    assert "kIdleClassIndex = 2" in rendered_main
