"""
ui/tokens.py — Hệ thống Design Tokens trung tâm cho toàn bộ UI.

Tập trung quản lý màu sắc, kích thước, font chữ và các hằng số stylesheet.
Hỗ trợ đa ngôn ngữ (Tiếng Việt) và đảm bảo tính nhất quán của giao diện.
"""

from PyQt6.QtCore import QSize
from ui.palettes import LIGHT_PALETTE, DARK_PALETTE
from ui.color_utils import readable_text_on

_p = LIGHT_PALETTE

# ── Semantic Colors (Claude Web Aesthetic) ──────────────────────────────────
COLOR_SURFACE_PRIMARY = _p.SURFACE_SECONDARY   # App background / Canvas (#F5F5F7)
COLOR_SURFACE_RAISED  = _p.SURFACE_PRIMARY     # Cards / Panels / Elevated surfaces (#FFFFFF)
COLOR_SURFACE_TERTIARY = _p.SURFACE_TERTIARY   # Inputs / Secondary panels

COLOR_TEXT_PRIMARY   = _p.TEXT_PRIMARY
COLOR_TEXT_SECONDARY = _p.TEXT_SECONDARY
COLOR_TEXT_MUTED     = _p.TEXT_TERTIARY

COLOR_BORDER_DEFAULT = _p.BORDER
COLOR_BORDER_SUBTLE  = _p.BORDER_LIGHT

COLOR_ACCENT_PRIMARY = _p.PRIMARY
COLOR_ACCENT_HOVER   = _p.PRIMARY_LIGHT

COLOR_STATUS_SUCCESS = _p.STATUS_SUCCESS
COLOR_STATUS_WARNING = _p.STATUS_WARNING
COLOR_STATUS_DANGER  = _p.STATUS_ERROR

# ── Typography ─────────────────────────────────────────────────────────────
APP_FONT_STACK = "'Geist', 'Plus Jakarta Sans', 'Be Vietnam Pro', 'SF Pro Display', 'Segoe UI', sans-serif"
TITLE_FONT_STACK = "'PP Editorial New', 'Clash Display', 'Geist', 'Be Vietnam Pro', sans-serif"
MONO_FONT_STACK = "'JetBrains Mono', 'SF Mono', 'Cascadia Code', monospace"

# ── Geometry & Border Radius ───────────────────────────────────────────────
RADIUS_CARD = "16px"
RADIUS_BUTTON = "10px"
RADIUS_INPUT = "8px"
RADIUS_PILL = "6px"

CROP_REGION = (0, 122, 255, 40)

# ── Spacing & Margins ──────────────────────────────────────────────────────
SPACE_PAGE = 24
SPACE_CARD_PADDING = 20
SPACE_SECTION_GAP = 16
SPACE_ELEMENT_GAP = 12
SPACE_TINY = 8

# ── Dimensions ─────────────────────────────────────────────────────────────
SHELL_SIDEBAR_W = 280
SHELL_NAV_H = 48
SHELL_BRAND_H = 72
SHELL_BRAND_ICON = QSize(28, 28)
SHELL_NAV_ICON = QSize(20, 20)

BTN_H = 32
BTN_SMALL_H = 28
SETTINGS_BTN_H = 32
SETTINGS_INPUT_H = 32
SPELL_BTN_H = 32
PROGRESS_H = 8
LABEL_W = 180

RECORD_GRAPH_MIN_H = 220
RECORD_LIST_MIN_H = 260
SETTING_CONSOLE_MIN_H = 260
STATISTICS_FFT_MIN_H = 380
STATISTICS_SAMPLE_LIST_MIN_H = 260
WAND_SPELL_LIST_MIN_H = 260
WAND_TERMINAL_MIN_H = 260
TERM_MIN_H = 260

RIGHT_MAX_W = 320
RIGHT_MIN_W = 320

# ── Colors for Plotting (IMU) ──────────────────────────────────────────────
PLOT_AX_COLOR = "#F28BA8"
PLOT_AY_COLOR = "#9FB7F4"
PLOT_AZ_COLOR = "#9ED9C7"
PLOT_GX_COLOR = "#F4B183"
PLOT_GY_COLOR = "#B7A5F5"
PLOT_GZ_COLOR = "#86C5F3"
PLOT_HANDLE_HOVER_COLOR = "#7C9CE6"


# ── Legacy Constants & QSS (Will be cleaned up in Phase 4) ─────────────────
# Mappings to prevent import errors in pages that haven't been updated yet.
# To avoid QSS anti-pattern, most are empty strings relying on theme.py.
# We only preserve string templates that use .replace or .format.

SURFACE_1 = COLOR_SURFACE_RAISED
SURFACE_2 = COLOR_SURFACE_TERTIARY
TEXT_PRIMARY = COLOR_TEXT_PRIMARY
TEXT_SECONDARY = COLOR_TEXT_SECONDARY
TEXT_TERTIARY = COLOR_TEXT_MUTED
TEXT_MUTED = COLOR_TEXT_MUTED
TEXT_BODY = COLOR_TEXT_SECONDARY
BORDER = COLOR_BORDER_DEFAULT
BORDER_COLOR = COLOR_BORDER_DEFAULT
BORDER_MID = COLOR_BORDER_DEFAULT
DANGER = COLOR_STATUS_DANGER
DANGER_TEXT = "#FFFFFF"
WARNING = COLOR_STATUS_WARNING
SUCCESS = COLOR_STATUS_SUCCESS
ACCENT = COLOR_ACCENT_PRIMARY
PRIMARY_COLOR = COLOR_ACCENT_PRIMARY
PRIMARY_LIGHT = COLOR_ACCENT_HOVER
PRIMARY_DARK = COLOR_ACCENT_HOVER
ACCENT_TEXT = "#FFFFFF"
HOVER_BG = "rgba(0, 0, 0, 0.04)"
SHADOW_COLOR = "rgba(0, 0, 0, 0.04)"

CARD_RADIUS = RADIUS_CARD
BTN_RADIUS = RADIUS_BUTTON
INPUT_RADIUS = RADIUS_INPUT
CARD_INNER_RADIUS = "12px"
CARD_OUTER_RADIUS = RADIUS_CARD
SURFACE_0 = COLOR_SURFACE_PRIMARY
V_SURFACE_DEFAULT = COLOR_SURFACE_PRIMARY
V_SURFACE_RAISED = COLOR_SURFACE_RAISED
BG_WHITE = COLOR_SURFACE_RAISED
BG_DARK = COLOR_SURFACE_TERTIARY

BADGE_RADIUS = "999px"
CARD_BEZEL = 4

RARITY_NONE = "#94A3B8"
RARITY_COM  = "#10B981"
RARITY_UNC  = "#3B82F6"
RARITY_RARE = "#8B5CF6"
RARITY_EPIC = "#F59E0B"

WAND_ACCENT = PRIMARY_COLOR
SETTINGS_ACCENT = PRIMARY_COLOR

MARGIN_COMFORTABLE = SPACE_PAGE
SPACING_LG = SPACE_PAGE
SPACING_MD = SPACE_SECTION_GAP
SPACING_SM = SPACE_ELEMENT_GAP
SPACING_XS = SPACE_TINY

SPACE_4 = 4
SPACE_8 = 8
SPACE_12 = 12
SPACE_16 = 16
SPACE_24 = 24
SPACE_32 = 32

STYLE_SCROLL_AREA = ""
STYLE_TRANSPARENT_WIDGET = ""
STYLE_HOME_SECTION_TITLE = ""
STYLE_HOME_SECTION_SUBTITLE = ""
STYLE_SECTION_LABEL_TEMPLATE = ""
STYLE_STATE_EMPTY_TITLE = ""
STYLE_STATE_EMPTY_BODY = ""

STYLE_BTN_PRIMARY = ""
STYLE_BTN_OUTLINE = ""
STYLE_BTN_BASE = ""
STYLE_BTN_START = ""
STYLE_BTN_STOP = ""
STYLE_BTN_SNIP = ""
STYLE_BTN_DANGER_OUTLINE = ""
STYLE_BTN_BACK = ""
STYLE_BTN_SMALL = ""

STYLE_RECORD_MAIN_CONTAINER = ""
STYLE_RECORD_GRAPH_CARD = ""
STYLE_RECORD_FIELD_LABEL = ""
STYLE_RECORD_LIST = ""
STYLE_RECORD_COMBO = ""
STYLE_RECORD_CURRENT_SPELL = ""
STYLE_RECORD_METRIC_VALUE = ""

STYLE_STATISTICS_CARD = ""
STYLE_STATISTICS_BTN_BACK = ""
STYLE_STATISTICS_LIST = ""
STYLE_STATISTICS_CURRENT_SPELL = ""
STYLE_STATISTICS_INFO_LABEL = ""
STYLE_STATISTICS_META_LABEL = ""

STYLE_SETTING_CARD = ""
STYLE_SETTING_BTN_OUTLINE = ""
STYLE_SETTING_BTN_PRIMARY = ""
STYLE_SETTING_BTN_DANGER = ""
STYLE_SETTING_INPUT = ""
STYLE_SETTING_CHECKBOX = ""
STYLE_SETTING_PROGRESS = ""
STYLE_SETTINGS_FORM_LABEL = ""
STYLE_SETTINGS_INPUT_INVALID = ""
STYLE_SETTINGS_SECTION_LABEL_TEMPLATE = ""

STYLE_PROGRESS = ""
STYLE_WAND_COMBO = ""
STYLE_WAND_LIST_TITLE = ""
STYLE_WAND_SPELL_NAME = ""
STYLE_WAND_SPELL_COUNT = ""
STYLE_WAND_TERMINAL_CARD = ""
STYLE_WAND_STATS_CARD = ""

STYLE_CONSOLE = ""
STYLE_TERMINAL = ""

STYLE_RECORD_STATUS_TEMPLATE = "font-family: {app_font}; color: {color}; font-weight: 700; font-size: 11px;".replace("{app_font}", APP_FONT_STACK)
STATUS_LABEL_STYLE_TEMPLATE = STYLE_RECORD_STATUS_TEMPLATE
STYLE_WAND_FLASH_STATUS = STYLE_RECORD_STATUS_TEMPLATE
STYLE_SETTINGS_HINT_TEMPLATE = "font-family: 'Geist', sans-serif; color: {color}; font-size: 11px; line-height: 1.5;"
STYLE_WAND_EMPTY_ROW_TEMPLATE = "font-family: 'Geist', sans-serif; color: {color}; font-size: 11px; font-style: italic; padding: 12px;"
